name: python-ci

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"
      fail-fast:
        required: false
        type: boolean
        default: false
      skip-lint:
        required: false
        type: boolean
        default: false
      tox-lint-env:
        required: false
        type: string
        default: "lint"
      tox-test-env:
        required: false
        type: string
        default: "py"
      upload-coverage:
        required: false
        type: boolean
        default: false
    secrets: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.6.2"
          enable-cache: true
      - name: Install tox and tox-gh-actions
        run: uv pip install tox tox-gh-actions
      - name: Setup tox cache
        uses: actions/cache@v3
        with:
          path: .tox
          key: ${{ runner.os }}-tox-${{ inputs.python-version }}-${{ hashFiles('**/pyproject.toml', '**/setup.py', '**/tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-${{ inputs.python-version }}-
      - name: Run lint
        if: ${{ !inputs.skip-lint }}
        run: tox -e ${{ inputs.tox-lint-env }}
      - name: Run tests
        run: tox
      - name: Upload coverage to Codecov
        if: ${{ inputs.upload-coverage }}
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false 