name: python-public-release

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"
      test-matrix:
        required: false
        type: boolean
        default: true
      build-args:
        required: false
        type: string
        default: ""
      publish-to-testpypi:
        required: false
        type: boolean
        default: false
      check-description:
        required: false
        type: boolean
        default: true
    secrets:
      pypi-token:
        required: true
      testpypi-token:
        required: false

jobs:
  call-ci:
    if: inputs.test-matrix == true
    uses: ./.github/workflows/python-ci.yml
    secrets: inherit

  build-publish:
    needs: call-ci
    if: ${{ always() && (!inputs.test-matrix || success()) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      
      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.6.2"
          enable-cache: true
      
      - name: Install build dependencies
        run: uv pip install build twine ${{ inputs.build-args }}
      
      - name: Build sdist/wheel
        run: python -m build
      
      - name: Check package description
        if: ${{ inputs.check-description }}
        run: twine check dist/*
      
      - name: Publish to TestPyPI
        if: ${{ inputs.publish-to-testpypi }}
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          user: __token__
          password: ${{ secrets.testpypi-token }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          user: __token__
          password: ${{ secrets.pypi-token }}
          skip-existing: true