name: python-ci

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"
      run-lint:
        required: false
        type: boolean
        default: true
      run-typecheck:
        required: false
        type: boolean
        default: true
      upload-coverage:
        required: false
        type: boolean
        default: false
    secrets: {}

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: true
          virtualenvs-in-project: true
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            .venv
            .tox
          key: ${{ runner.os }}-deps-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock', '**/pyproject.toml', '**/tox.ini') }}
      
      - name: Install dependencies
        run: poetry install
      
      - name: Run lint
        if: ${{ inputs.run-lint }}
        run: poetry run tox -e lint
        
      - name: Run typecheck
        if: ${{ inputs.run-typecheck }}
        run: poetry run tox -e typecheck
        
      - name: Run tests
        run: poetry run tox
      
      - name: Upload coverage
        if: ${{ inputs.upload-coverage }}
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false 