name: python-ci

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"
      run-lint:
        required: false
        type: boolean
        default: true
      run-typecheck:
        required: false
        type: boolean
        default: true
      upload-coverage:
        required: false
        type: boolean
        default: false
      use-poetry:
        required: false
        type: boolean
        default: false
    secrets: {}

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
      
      - name: Install Poetry
        if: ${{ inputs.use-poetry }}
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: true
          virtualenvs-in-project: true
      
      - name: Cache tox environments
        uses: actions/cache@v3
        with:
          path: .tox
          key: ${{ runner.os }}-tox-${{ inputs.python-version }}-${{ hashFiles('**/pyproject.toml', '**/setup.py', '**/tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-${{ inputs.python-version }}-
      
      - name: Install dependencies with Poetry
        if: ${{ inputs.use-poetry }}
        run: poetry install
      
      - name: Install tox with pip
        if: ${{ !inputs.use-poetry }}
        run: pip install tox tox-gh-actions
      
      - name: Run lint
        if: ${{ inputs.run-lint }}
        run: |
          if [ "${{ inputs.use-poetry }}" == "true" ]; then
            poetry run tox -e lint
          else
            tox -e lint
          fi
        
      - name: Run typecheck
        if: ${{ inputs.run-typecheck }}
        run: |
          if [ "${{ inputs.use-poetry }}" == "true" ]; then
            poetry run tox -e typecheck
          else
            tox -e typecheck
          fi
        
      - name: Run tests
        run: |
          if [ "${{ inputs.use-poetry }}" == "true" ]; then
            poetry run tox
          else
            tox
          fi
      
      - name: Upload coverage
        if: ${{ inputs.upload-coverage }}
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false 